language: node_js
node_js:
  - "v8.0.0"
services:
  - postgresql
  before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
before_script:
  - cp config/database.yml.travis config/database.yml
